-- Luacheck configuration for Wars Selection mods
-- Game-engine globals are injected by the runtime, so declare them here.

std = "max"

globals = {
    -- Engine root object
    "root",
    "gameplay",
    -- Parameter getters
    "getParameter",
    "getParameterNumber",
    "getParameterBoolean",
    -- Mod registration
    "addMod",
    -- Serialization
    "toJson",
    "fromJson",
    -- Engine callbacks defined by mods
    "onInit",
    "onPlayerEliminate",
    "onStart",
    "onTick",
    -- mods/adjust_resources
    "BERRY_AMOUNT",
    "BIG_FISH_AMOUNT",
    "IRON_AMOUNT",
    "SMALL_FISH_AMOUNT",
    "STONE_AMOUNT",
    "WHEAT_AMOUNT",
    "WOOD_PCT",
    "TAG_BERRY",
    "TAG_BIG_FISH",
    "TAG_IRON",
    "TAG_SMALL_FISH",
    "TAG_STONE",
    "TAG_WHEAT",
    "TAG_WOOD",
    "ForEachTagged",
    "ScaleResource",
    "SetResource",
    -- mods/default_gameplay_functions
    "getAgeFaction",
    "getAgeFactionIndustrial",
    "id",
    -- mods/diplomacy (interface + backend)
    "Diplomacy",
    "DiplomacyInterface",
    "GlobalNotif",
    "RequestNotif",
    "SystemNotif",
    "SendGlobalMsg",
    "SendRequestMsg",
    "SendSystemMsg",
    "ServerDiplomacyHandler",
    "SetMusicOnStart",
    "allySound",
    "checkStatus",
    "checkStatusFrontend",
    "currentAction",
    "currentP1",
    "currentP2",
    "currentRQ",
    "currentWork",
    "declareWar",
    "finsihSound",
    "getAllyCount",
    "getFactionOfPlayer",
    "getNodes",
    "getPlayerName",
    "getPlayerOfFaction",
    "hideShow",
    "openingSound",
    "Pay",
    "Peace",
    "peaceSound",
    "requestSound",
    "setAlly",
    "showPosition",
    "updateGamePlay",
    "warSound",
    "winControlDiplomacy",
    -- mods/diplomacy/ui_framework
    "Image",
    "Interface",
    "Label",
    "Panel",
    "Root",
    "Widget",
    -- mods/starting_resources
    "initOnStartResourcesInit",
    "initResourcesA",
    -- mods/victory_conditions
    "ROI_ID",
    "checkFactionLose",
    "checkWinTeam",
    "func",
    "func_",
    "losePlayer",
    "makePlayerLose",
    "onScriptWinLoss",
    "onTickWinLoss",
    "winTeam",
    -- mods/wave (wave_PVE)
    "WAVE_SCRIPT_VERSION",
    "TC_CLOSE_AREA_SHIFT",
    "MAKE_UNITS",
    "DEBUG",
    "DEFENDER_FLAG_TYPE",
    "ATTACKER_FLAG_TYPE",
    "AUTO_WALL_ATTACK",
    "WONDER_WIN_MIN_MOMENT",
    "WONDER_WIN_TIME_TO_WIN",
    "FIRST_WAVE_TIME",
    "WAVE_INTERNAL",
    "TIER_INTERNAL",
    "PLAYER_WEIGHT",
    "ATTACK_MODE",
    "ATTACKER_FACTION_ID",
    "FINAL_AGE",
    "BUILD_WONDER",
    "PENALTY",
    "MAX_PENALTY_FACTOR",
    "MAX_ATTACKER_UNITS",
    "MAX_UNITS_PER_WAVE",
    "IDLE_REDIRECT_INTERVAL",
    "IDLE_REDIRECT_LIMIT",
    "REDIRECT_BATCH_SIZE",
    "COMMAND_BATCH_SIZE",
    "WONDER_CHECK_INTERVAL",
    "FACTION_SIZE",
    "ATTACKER_POSITIONS",
    "UNIT_BATCHES",
    "ShowOpeningMessage",
    "WaveDebug",
    "FindUnitIDByTypeID",
    "GetUnitpositionByUnitID",
    "CreatUnits",
    "FindAttackerFactionID",
    "GetControlledFactionOfPlayer",
    "GetAttackerSpawnPositions",
    "GetDefenderpositions",
    "FindLatestPlayerAge",
    "GetVector",
    "DotProduct",
    "Determinant",
    "Magnitude",
    "Atan2Compatible",
    "GetVectorAngleCounterClockwise",
    "GetDirectionAngle",
    "RadiansToGameDirection",
    "GetMinKey",
    "GetNearestDefenderFaction",
    "GetRandomDefenderFaction",
    "GetSpawnUnitAllocation",
    "FindIdleAttackerUnits",
    "FindAllMobileAttackerUnits",
    "CreateAttackOrderDirected",
    "RedirectUnitsToLivingDefenders",
    "RedirectUnitsByAttackMode",
    "CreateAttackPaths",
    "SetFinalAge",
    "JsonDecode",
    "ProcessPendingRedirect",
    "onResearchDone",
}

-- Engine-provided helpers that mods only call, never assign
read_globals = {
    "addInterface",
    "addScriptFunction",
    "addStartFunction",
    "addTickFunction",
    "forEachControlledFaction",
    "forEachPlayerFaction",
    "forEachPlayerLive",
    "forEachPlayerUnit",
    "forEachPlayerUnit2",
    "genServerData",
    "getParameterBool",
    "getResult",
    "isResearchComplete",
    "key",
    "killAllMovableUnits",
    "log",
    "numbersToString",
    "onPlayerLose",
}

-- Keep the config permissive so existing mods pass;
-- 6xx codes are pure formatting noise (whitespace / line length) in mod files.
ignore = { "21", "22", "23", "31", "32", "41", "42", "43", "53", "54", "611", "612", "631" }
